### PR TITLE
STOR-1606: Bump OLM metadata to 4.17

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-1606
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
From CI logs: new 4.17 version number is reflected in the [CSV](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_gcp-filestore-csi-driver-operator/96/pull-ci-openshift-gcp-filestore-csi-driver-operator-main-operator-e2e/1811089655865544704/artifacts/operator-e2e/gather-extra/artifacts/oc_cmds/clusterserviceversions).

**Comment by Phaow** [comment]
/label qe-approved
The 1 failed job is a flaky(1 test case).

**Pull request merged**
