### PR TITLE
[4.17] OCPBUGS-44363: add WIF support

### PR DESCRIPTION
**Pull request by RomanBednar**
cc @openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
@chao007  Putting it on hold for now - what's the status of 4.18 testing? Are we done or close to done with testing?

**Comment by chao007** [comment]
Regression testing on 418 is passed. Prefer to merge it first and track back port by bug [OCPBUG 44363](https://issues.redhat.com/browse/OCPBUGS-44363).

**Pull request merged**
