### PR TITLE
STOR-1317,STOR-1318: Refactor for transition from TP to GA

### PR DESCRIPTION
**Pull request by tsmetana**
This is a partial revert of changes that were made to build the TP bundles. Also changes the IAM role request to conform to the upstream manifests.

### CODE REVIEW

**Comment by tsmetana** [comment]
To testy the changes I built the bundle in my quay repo. It should be testable using this CatalogSource:
```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: gcp-filestore
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/tsmetanarh/gcp-filestore-csi-driver-index
```
Basic smoke tests look to be OK so far.

**Comment by jsafrane** [comment]
CI complains:

>   - message: 'constraints not satisfiable: no operators found in channel preview of
      package gcp-filestore-csi-driver-operator in the catalog referenced by subscription
      oo-xq4gg, subscription oo-xq4gg exists'

Do you want to fix it before this PR is merged? 
https://github.com/openshift/release/blob/967c060f5ac20b4826311d432f52094ddf2ee764/ci-operator/config/openshift/gcp-filestore-csi-driver-operator/openshift-gcp-filestore-csi-driver-operator-main.yaml#L121

(+ 4.14 / 4.15 files)

**Comment by jsafrane** [comment]
e2e succeeded \o/
/lgtm

**Comment by jsafrane** [comment]
/lgtm cancel
just testing github approvals

**Review by jsafrane — APPROVED** [review]
this should lgtm the request automatically

**Pull request merged**
