### PR TITLE
STOR-1065: Rework sidecar bindings to bind common ClusterRoles

### PR DESCRIPTION
**Pull request by mpatlasov**
PR https://github.com/openshift/cluster-storage-operator/pull/379 published builiding blocks of sidecar ClusterRoles. Now, gcp-filestore csi driver operator may compose its sidecars ClusterRoles from those building blocks.

This PR also moves permissions for `leases` resource from ClusterRole to per-namespace Role (`assets/rbac/lease_leader_election_role.yaml`).

### CODE REVIEW

**Comment by ropatil010** [comment]
Currently this is blocker or unable to test as we can not provision volumes with gcp file store provisioner.
Error and Discussion have updated here [STOR-1363](https://issues.redhat.com/browse/STOR-1363#:~:text=Error%20for%20GCP%20Filestore%3A)

**Comment by mpatlasov** [comment]
`ci/prow/operator-e2e-extended` is perma failing, see https://github.com/openshift/gcp-filestore-csi-driver-operator/pull/40.

**Comment by mpatlasov** [comment]
`ci/prow/operator-e2e` is perma failing, see https://github.com/openshift/gcp-filestore-csi-driver-operator/pull/43

**Comment by ropatil010** [comment]
/label qe-approved
Test results updated here: [STOR-1363](https://issues.redhat.com/browse/STOR-1363#:~:text=Red%20Hat%20Employee-,Platform%3A%20GCP,-Payload%3A%204.14.0%2D0)

**Pull request merged**
