### PR TITLE
OCPBUGS-4535: Bump version to 4.13

### PR DESCRIPTION
**Pull request by locriandev**
Ref. https://issues.redhat.com/browse/ART-5087

### CODE REVIEW

**Comment by RomanBednar** [comment]
/lgtm
/label docs-approved
/label px-approved

Adding docs and px labels - this is not a user facing change.

**Comment by locriandev** [comment]
@RomanBednar PR is still missing `qe-approved` label. As an alternative, how could I get the `bugzilla/valid-bug` instead?

**Comment by dobsonj** [comment]
Turns out we just got a bug filed, so let's use this one:
/retitle OCPBUGS-4535: Bump version to 4.13

**Comment by RomanBednar** [comment]
@locriandev with the bug being added and linked it should be ok to merge this now.

**Comment by dobsonj** [comment]
It should merge in a moment, or after the retest completes I guess.
Also in the future I think it's fine to add qe-approved ourselves for release chores like this that are not being pre-merge tested.

**Pull request merged**
